### ISSUE TITLE
Schvalenie katalogu poziadaviek.

### ISSUE THREAD

**Issue by FilipKerak** [TIS2019-FMFI/konverzia-ohlasov#21]
https://github.com/TIS2019-FMFI/konverzia-ohlasov/blob/documentation/katalog_poziadaviek.pdf

finálna verzia katalógu požiadaviek.

**Comment by pavelpetrovic** [comment]
dakujem za aktualizaciu KP. uz len drobne poznamocky:
 - PP-1AP-2: PP-1AP-3: su tieto parametre povinne? ak ano, zdoraznite to.
 - PP-1AP-7: bude vložený reťazec - je retazec v tom ISO formate tiez jednoriadkovy? ak ano, tak fajn, ak nie, tak prosim upresnite co tam bude
 - SP-1AP-1: sucasne s novymi alebo ked sa pusti s nejakym inym parametrom? prosim upresnit
 - SP-2AP-2: to iste
zvazte, pripadne zapracujte a ked to budete mat, tak, prosim, poslite KP zadavatelke a poziadajte ju, aby si ho dokladne prestudovala a dala k nemu spatnu vazbu na pripadne upravy, lebo podla schvalenej verzie system vyviniete. drzim palce a tesim sa na dalsie stretnutie.
