### ISSUE TITLE
Naprogramovat triedy z Class diagramu

### ISSUE THREAD

**Issue by nikolahornikova** [TIS2019-FMFI/konverzia-ohlasov#28]

**Comment by nikolahornikova** [comment]
blocked by #30 #31 #32 #33 #34 #35

**Comment by pavelpetrovic** [comment]
nezabudajte, prosim, ze rezim prace ma by taky, ze:
* posledna skompilovatelna verzia je v master branch
* ked niekto ide urobit nejaku svoju malu cast, tak si od master odvodi novy vlastny branch
* akonahle dokonci svoje upravy, robi pull request na master branch
* upravy si _pozrie_ niekto iny, bud to okomentuje, ze niecomu nerozumie, alebo sa mu nezda (a nasleduju upravne commity), alebo nakoniec urobi approving review a branch sa mergne do master branch a nasledne vymaze

dakujem.
