### ISSUE TITLE
Pridat referncie a odkazy do katalogu.

### ISSUE THREAD

**Issue by FilipKerak** [TIS2019-FMFI/konverzia-ohlasov#4]
tu je odkaz na zdielany dokument bolo by treba dopnit body ohladom odkazov a referncii
teda 1.3, 1.4, 4
https://drive.google.com/file/d/1Yexi9_Wc6qZT-iGEOEsVIJLhI45eC5fb/view?usp=sharing

**Comment by IvetBx** [comment]
Pridala som tie odkazy a slovnik. Skuste to pozriet, pripadne doplnit, ak by trebalo nieco viac.
