### ISSUE TITLE
Doplnenie katalogu poziadaviek o vseobecne popisy

### ISSUE THREAD

**Issue by FilipKerak** [TIS2019-FMFI/konverzia-ohlasov#5]
Do katalogu poziadaviek treba doplnit vseobecne popisy a perspektivu. Body 1.1, 1.5, 2.1
https://drive.google.com/file/d/1Yexi9_Wc6qZT-iGEOEsVIJLhI45eC5fb/view?usp=sharing

**Comment by Mr4v3c** [comment]
Body 1.1, 1.5 a 2.1 v katalogu doplnene
