### ISSUE TITLE
Korektura katalogu poziadaviek

### ISSUE THREAD

**Issue by FilipKerak** [TIS2019-FMFI/konverzia-ohlasov#7]
Opravit chyby v katalogu a odoslat ho na schvalenie.

**Comment by pavelpetrovic** [comment]
ďakujem za výbornú prácu. preštudoval som si Váš KP a tu sú moje pripomienky, ktoré, prosím, zapracujte:

PP-1AP-1
  - zistite, či netreba upresniť web services
    (môže sa stať, že je tam viac rôznych spôsobov a Vy máte použiť jeden konkrétny)
    ak nie, tak to netreba meniť, aj keď upresniť určite nezaškodí, to by ste mohli tak či tak

PP-1AP-2
  požadovaných parametrov:
    prosím detailne rozpísať všetky možnosti

PP-1AP-4
  1.  nerozumiem, čo sú doplnkové dáta
  2.  ktoré všetky typy ohlasov a publikácií systém bude podporovať (treba podrobne rozpísať, alebo sa niekam odkázať)
  3.  nie je jasné, či sa doplnkové dáta ťahajú zvlášť alebo už na prvý dopyt

PP-1AP-6
  bude názov a umiestnenie súboru nejak určené?

PP-1AP-8
  ako budú tieto chybné záznamy v logu označené? ako bude ten log vyzerať? treba uviesť podrobný formát alebo sa niekam odkázať

PP-2AP-1
  "systém knižnice" nevidím v slovníku pojmov, čo to je?

PP-2AP-2
  - lepšie vysvetliť spoluprácu dvoch aplikácií:
     - ako bude 2AP vedieť, ktorý súbor má načítať?
     - je možné najskôr viackrát popúšťať 1AP a potom k tomu príslušne 2AP?
     - čo sa stane so súbormi na prenos dát medzi 1AP a 2AP? treba ich mazať ručne?

PP-2AP-3
  - priveľmi všeobecné, treba to presne podrobne a jednoznačne rozpísať

PP-2AP-4
  - to isté ako pri PP-1AP-8

SP-1AP-1
  - keby som nevedel o čo ide, tak to z tohto určite nepochopím, treba to v texte niekde dostatočne podrobne vysvetliť

SP-1AP-2
  - v požiadavke vôbec nie je uvedené, čím sa to líši od bežného PP-1AP-4 až PP-1AP-7

SP-1AP-3
  - to isté ako pri PP-1AP-8

SP-2AP-4
  - nemusíte dvakrát písať to isté, stačí keď napíšete že je to to isté ako PP-1AP-5 ale pre zmenené ohlasy

NF-A6
  - nerozumiem

**Comment by FilipKerak** [comment]
Zapisal som vacsinu zmien okrem SP-1AP-1 a PP-1AP-1. Zmeny su v zdielanom dokumente.

**Comment by pavelpetrovic** [comment]
len pre istotu: predpokladam, ze tato sprava este nepatrila mne, lebo ja ziadnu linku na zdielany dokument nemam. ked zapracujete vsetky, tak ma prosim notifikujte aj s linkou na dokument, ktory si mam pozriet. dakujem.

**Comment by IvetBx** [comment]
Tu je opravena verzia katalogu poziadaviek. https://drive.google.com/file/d/1Yexi9_Wc6qZT-iGEOEsVIJLhI45eC5fb/view?usp=sharing

**Comment by pavelpetrovic** [comment]
uz je vsetko super, len pridajte nadpis a svoje mena
v 1.2. deduplikacia -> aktualizacia
pridat odkaz na popis internetho formatu zoznamu citacii v poli 591
(pripominam, ze chcete zistit ci timestamp funguje aj odkedy dokedy, aby nedoslo k tomu, ze dostanete citacie pre publikacie, ktore este neboli importovane napr.)
3.1. - nazvy poziadaviek dajte rovno vedla znacky, napr. hlavne nech vidim na prvy pohlad, ze je to nazov
PP-1-AP3:  je treba  prosim preformulovat
PP-1-AP4: formuloval by som to od System bude.... a len sa odkazat kde tie typy su zdokumentovane.
PP-1-AP6 su kombinovane 3 poziadavky
PP-2-AP-2 Súbory treba pre obmedzenie vzniku konfliktov vkladať postupne.
celkovo prosim upravte formulacie tak, aby zodpovedali tomu, ze poziadavky su poziadavky nie na vyvojovy tym, ale na funkcionalitu aplikacie - aku hodnotu aplikacia ponuka, poskytuje, zabezpecuje, vytvara, prinasa, atd. pre pouzivatela. tym vzdy zacnite vetu a prip. podrobnosti doplnte za to.
