### ISSUE TITLE
Odoslanie katalogu na schvalenie

### ISSUE THREAD

**Issue by nikolahornikova** [TIS2019-FMFI/konverzia-ohlasov#8]

**Comment by pavelpetrovic** [comment]
k poslednej verzii KP:

dakujem za rychle upravy, mozete si opravit dlzen v "informácia o publikácií," :-)

je to zatial strasne a hroza a treba to znovu prerobit.

2.2. "dáta o nových ohlasoch na citácie"
halo? kto tam? sprechen sie slowakisch?

v slovniku s objavuje "Školský systém", ale nikde inde v dokumente to nie je pouzite.
terminologia je dolezita a treba ju pouzivat konzistentne. naviac, pokial viem
Virtua nie je databaza publikacnej cinnosti, ako v slovniku uvadzate, ale komplexny
kniznicny system. vsetko, co je v dokumente uvedene, ma byt presne a pravdive.
v texte toto oznacujete minimalne 2-3 inymi terminmi

ku konkretnym poziadavkam:

PP-1AP-1:
toto: "Knižnica si každý večer aktualizuje databázu publikácií pomocou týchto služieb.
Vytváraný systém sa bude pripájať na rovnaké služby ako sú už zaužívané."
je stale mizerna formulacia. Kto je to "kniznica", deje sa to automaticky? ak ano, preco
to tu nie je napisane? Co je zauzivane? Nic nie je zauzivane, lebo citacie sa zatial
netahaju, tak nie je nic zauzivane. Za akym ucelom sa bude pripajat? Kazda poziadavka
ma byt pisana ako hodnota pre pouzivatela za nejakym ucelom. To tam ale nie je
uvdene!!

PP-1AP-2:
ale co by. katastrofa. asi nie vsetkych ohlasov, ale len novych, nie? tym padom, to co
je v tejto poziadavke napisane NIE JE PRAVDA!!!
Kazda poziadavka musi byt jasna zrozumitelna a davat zmysel bez toho, aby clovek
musel precitat dalsich 5 a zistovat, ako su navzajom v konflikte a robit si inferenciu moznych
pripadov, aby zistil CO ASI TAK AUTOR TYM CHCEL POVEDAT!!! :( :(

PP-1AP-3:
co su to "zmenene ohlasy"?? Doteraz o tom nebola vobec rec, ake zmenene ohlasy? o co ide?
preco si mam nieco domyslat? ako toto mam vobec chapat? naozaj iba zmenene ohlasy?
"unixovy timestamp" nie je v slovniku pojmov, co to je? pocet milisekund, ktore ubehli od 1.januara 1970?
alebo co?

PP-1AP-6:
to mi prosim vysvetlite, kde sa v stringu "data_na_zapis" nachadza presny datum a cas???

PP-1AP-7:
konflikt. prvy bod hovori, ze v logu budu len chybne zaznamy, druhy bod hovori, ze tam budu aj OK
co je cislo riadku? cislo riadku logu? to naozaj treba? ved ked to otvorim v hociakom editore, tak
vidim na ktorom riadku som, ci? nerozumiem.
pre OK - nemal by tam byt okrem vlozeneho retazca aj nejaky odkaz (ID?) na evidovanu publikaciu,
ku ktorej vkladany zoznam citacii patri?

PP-2AP-2:
nadpis hovori o priecinku ale text hovori o subore, he? ktore subory sa nezmazu? co ak nezada parameter?

PP-2AP-4: ten isty problem ako pri 1AP

SP-1AP-1: slovo "treba" nepouzivajte. ako ziskat? a co znamena identifikovat?

SP-1AP-2: v com je toto ine ako PP-1AP-7? na prvy pohlad to vyzera identicky!

SP-2AP-3: To isté ako PP-1AP-5
 => ked je to to iste, tak to nepiste, ak je to v niecom ine, tak napiste v com je to ine.

SP-2AP-4: nerozumiem preco je tu pouzite slovo deduplikacny, ked tam ziadna duplicita nie je, len sa robi UPDATE v danom poli prislusnej evidovanej publikacie

este mam navrh na jednu funkcionalitu:
  - ked sa aplikacie spustia bez argumentov, vypisu navod pouzitia.

NF-A6: by som prepisal napriklad takto:
Aplikacia konvertuje Nodes v XML formáte na polia vo formáte MARC21 podla <sem uviest odkaz na dokument, ktory to opisuje>.

PR-AP-4: mozete to, prosim, upresnit?
